### PR TITLE
Create mirror.cpp

### PR DESCRIPTION
**Pull request by ervaibhavkumar**
Added code to get mirror image of a tree in C++ language

Regards
Vaibhav

### CODE REVIEW

**Comment by ervaibhavkumar** [comment]
@m-sameer Please see if this works for you :)

**Comment by m-sameer** [comment]
Did you test this?

**Comment by ervaibhavkumar** [comment]
@m-sameer It's working for me

**Comment by m-sameer** [comment]
Cool then.

**Pull request merged**
