### PR TITLE
added mirror of a tree in data structures in java

### PR DESCRIPTION
**Pull request by doomers**
#59 
Mirror of a tree in java #

### CODE REVIEW

**Comment by BaReinhard** [comment]
what is the purpose of this class?

**Comment by doomers** [comment]
which class? class MIrror?

**Comment by BaReinhard** [comment]
yeah the mirror class or the mirror_of_a_tree file in general. What would this be used for?

**Comment by doomers** [comment]
It gives the mirror the tree, it's a very general and frequently asked
question in interviews.

**Comment by BaReinhard** [comment]
aside from being frequently asked in interviews what is the purpose behind it. Also would this still be considered a data structure or an algorithm.

Not trying to grill you, just trying to understand

**Comment by doomers** [comment]
Uhh... do you think Longest common subsequence, substring, minimum spanning tree is an algorithm???
the answer is no, they are problems solved using an algorithm basically a demonstration of a problem, same goes with the mirror of a tree it is a demonstration how traversing and swapping works in a binary tree.
same goes with bfs in tree and many other things in repo.

It's not just about an interview problem, it's more of generic and important question one must know, so i thought that should be included!

**Comment by BaReinhard** [comment]
Thanks for the clarification and nice work with the tree

**Comment by doomers** [comment]
you are welcome

**Pull request merged**
