### PR TITLE
Java 8 implementation of Histogram Equalization Algorithm

### PR DESCRIPTION
**Pull request by vn17**
This pull request resolves issue #60

### CODE REVIEW

**Comment by vn17** [comment]
Please add the Hacktoberfest label before you merge this PR.

**Comment by BaReinhard** [comment]
Hacktoberfest labels are not needed to receive credit for the 4 pull requests by hacktoberfest

**Comment by vn17** [comment]
Ok

**Comment by vn17** [comment]
Then please review my PR and let me know

**Comment by vn17** [comment]
Thanks @BaReinhard . I am not sure but the Jenkins hacktoberfest blog [here](https://jenkins.io/blog/2017/10/06/hacktoberfest/?utm_source=DigitalOcean_Hacktoberfest2017) says this 

> Hacktoberfest project requires issues and/or pull requests to be labeled with the `hacktoberfest` label

**Pull request merged**
