### PR TITLE
Fix grammar issues

### PR DESCRIPTION
**Pull request by m-sameer**
Fix some grammar issues in the README file.

### CODE REVIEW

**Comment by mhdsmr2** [comment]
@BaReinhard Please review this and merge it.

**Comment by BaReinhard** [comment]
reopen and I will merge it. Its been a crazy past couple months. Still trying to catch up with all the PRs and issues of existing projects

**Comment by m-sameer** [comment]
I deleted the repo. Do you want me to fork it again and create a new PR?

**Comment by m-sameer** [comment]
Would you like to give me write access to your repo? I will do a lot of work.

**Comment by BaReinhard** [comment]
I’ll give write access, I appreciate the help.

**Comment by m-sameer** [comment]
Okay. Thanks. Well, when'll you give them?

**Comment by BaReinhard** [comment]
I sent it already

**Comment by m-sameer** [comment]
Where have you sent it then?

**Comment by BaReinhard** [comment]
https://github.com/BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms/invitations

**Comment by m-sameer** [comment]
Do you want me to create a new PR?

**Comment by m-sameer** [comment]
@BaReinhard Please tell.

**Comment by BaReinhard** [comment]
you dont need to. whatever you feel is best

**Comment by m-sameer** [comment]
Okay.

**Pull request closed without merging**
